server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: papcrm123
    url: jdbc:mysql://34.118.36.189/PAPCRM
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: crmpap111@gmail.com
    password: sfmfidcscqondtjt

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000